name: Release TF Live

on: [push]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    name: check-formatting
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terragrunt
        uses: peter-murray/terragrunt-github-action@v1.0.0
        with:
          terragrunt_version: 0.27.0
      - name: Terragrunt Format Check
        run: terragrunt hclfmt --terragrunt-check

  release:
    runs-on: ubuntu-latest
    name: release
    if: github.ref == 'refs/heads/main'
    needs: check-formatting
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
